"""added module_enrollment model + recreated migration versions

Revision ID: a818d3d41c7c
Revises: 71f203a88100
Create Date: 2025-05-29 11:18:30.827204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a818d3d41c7c'
down_revision = '71f203a88100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_info_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['student_info_id'], ['student_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_info_id', 'module_id', name='unique_student_module')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_enrollments')
    # ### end Alembic commands ###
