"""Add Assessment model

Revision ID: d9a813d9a755
Revises: e87cbd61e204
Create Date: 2025-05-28 15:52:43.189585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a813d9a755'
down_revision = 'e87cbd61e204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('assessment_type', sa.Enum('egzaminas', 'uzduotis', 'testas', 'laboratorinis'), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('created_by_teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_teacher_id'], ['teacher_info.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    op.drop_table('assessments')
    # ### end Alembic commands ###
