"""updated module_enrollment

Revision ID: f1ce173ed5c1
Revises: a818d3d41c7c
Create Date: 2025-05-29 16:01:40.189003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ce173ed5c1'
down_revision = 'a818d3d41c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.Enum('rudens', 'pavasario'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_enrollments', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
